trigger:
  - master

pool:
  vmImage: 'ubuntu-22.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 7.0.x'
    inputs:
      version: 7.0.x

  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/Api/Api.csproj
      arguments: '-c Production -o obj/Docker/publish'
      zipAfterPublish: false
      modifyOutputPath: false
      workingDirectory: src/Api

  - task: Docker@2
    displayName: buildAndPush
    inputs:
      containerRegistry: 'DigitalOceanRegistry'
      repository: 'betsy-production/betsyapi'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest